apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lfmf703cw-nodejs
  janus-idp.io/tekton: lfmf703cw-nodejs
  backstage.io/kubernetes-id: lfmf703cw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lfmf703cw-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
