apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lfmf703cw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lfmf703cw-nodejs 
  name: lfmf703cw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lfmf703cw-nodejs 
